# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Site settings
title: "AI Insights Blog"
description: >
  Discover how to optimize the use of cutting-edge AI models like GPT-4, Gemini Ultra, and custom-made GPTs to revolutionize your workflow.
baseurl: "" # Leave this blank for the root directory
url: "https://tomsonius.github.io" # Update with your repository's URL

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Include these files in the build
include:
  - _posts
  - _layouts
  - _includes
  - assets

# Exclude these files from the build
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - test.py

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins configuration
jekyll-feed:
  path: feed.xml

jekyll-sitemap:
  changefreq: daily
  priority: 0.7

future: true
