title: Your Ultimate AI Guide
description: >
  Discover how to optimize the use of cutting-edge AI models like GPT-4, Gemini Ultra, and custom-made GPTs to revolutionize your workflow.
baseurl: "" # baseurl is blank for root directory
url: "https://tomsonius.github.io"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md

author:
  name: Your Name
  avatar: "/assets/images/avatar.png"
  bio: "AI enthusiast and tech blogger."

github: yourusername
twitter: yourusername

markdown: kramdown
highlighter: rouge
theme: minima

# Custom variables for styles
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"
body-font: 'Lora', 'Times New Roman', serif
header-font: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif
mid-col: "#808080"
