name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write  # Allow write access to the repository content
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Commit Gemfile.lock
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Gemfile.lock
        git commit -m "Update Gemfile.lock"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Using built-in GITHUB_TOKEN

    - name: Build the site
      run: bundle exec jekyll build

    - name: Upload site content
      uses: actions/upload-artifact@v4
      with:
        name: site
        path: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download site content
      uses: actions/download-artifact@v4.1.7
      with:
        name: site
        path: ./_site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Using GITHUB_TOKEN for deployment
        publish_dir: ./_site
