name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Commit Gemfile.lock
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Gemfile.lock
        git commit -m "Update Gemfile.lock"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

    - name: Build the site
      run: bundle exec jekyll build

    - name: Upload site content
      uses: actions/upload-artifact@v4
      with:
        name: site
        path: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download site content
      uses: actions/download-artifact@v4.1.7
      with:
        name: site
        path: ./_site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./_site
